# KoBERT 감정 다중분류모델

> KoBERT를 이용하여 한국어 문장을 여러 클래스로 분류하는 모델을 만들어 보려고 한다.
</br>
공포, 놀람, 분노, 슬픔, 중립, 기쁨, 혐오와 같은 감정이 느껴지는 대화 텍스트를 각각 어떠한 감정의 텍스트인지 분류하는 모델을 만드는 것이다. </br>
AIHUB에서 가져온 공공 데이터셋으로 KoBERT 자연어 처리 모델을 FineTuning하여 </br>
AI 감정 인식 일기 어플리케이션에서 작성한 일기 텍스트에서 감정을 추출하기 위한 목적으로 프로젝트를 진행하였다.

**KoBERT란?**

> BERT는 약 33억 개의 단어로 pretrain 되어 있는 기계번역 모델이다. </br>
하지만 외국에서 만든 것이다 보니 영어에 대해서는 정확도는 높고, 한국어에 대해서는 정확도가 떨어진다.</br>
따라서 BERT 모델을 한국어에도 잘 활용할 수 있도록 만들어진 것이 KoBERT이다. </br>
KoBERT는 BERT 모델에서 한국어 데이터를 추가로 학습시킨 모델로, 한국어 위키에서 5백만개의 문장과 5천4백만개의 단어를 학습시킨 모델이다. </br>
따라서 한국어 데이터에 대해서도 높은 정확도를 낼 수 있다고 한다. </br>
한국어의 불규칙한 언어 변화의 특성을 반영하기 위해 데이터 기반 토큰화 (Tokenization) 기법을 적용하여 기존 대비 27%의 토큰만으로 2.6% 이상의 성능 향상을 이끌어 낸 모델이다. </br>

# 1. 프로젝트 설명

**KoBERT 파인튜닝**
> BERT 모델은 자신의 사용 목적에 따라 파인튜닝(FineTuning)이 가능하다. </br>
따라서 Output layer만 추가로 달아주면 원하는 결과를 출력해내는 기계번역 모델을 만들어 낼 수 있다. </br>
이 점을 활용하여 KoBERT 모델을 FineTuning하여 최종적으로 일기 텍스트에서 감정을 추출해내는 모델을 새로 만들어 보려고 한다.

# 2. 데이터 수집

**데이터셋 구성에 따른 정확도 비교**
* 감성 대화 말뭉치 (AIHUB)
* 감정 분류를 위한 대화 음성 데이터셋 (AIHUB)
* 한국어 감정 정보가 포함된 단발성 대화 데이터셋 (AIHUB)
* 한국어 감정 정보가 포함된 연속적 대화 데이터셋 (AIHUB)

**KoBERT 모델의 파라미터는**
- learning_rate (학습률) : 5e^-5
- 에포크 수 : 5
- 배치 수 : 200
으로 진행하였다.

</br>

> **데이터셋 구성에 따른 모델의 정확도 비교는 다음과 같다.**

1. 연속적 데이터 + 단발성 데이터 + 감성대화 말뭉치
	</br>train acc 0.866
	</br>test acc 0.71
</br>
2. 연속적 데이터 + 단발성 데이터 + 감성대화 말뭉치(감정 별 대표 문장)
	</br>train acc 0.84
	</br>test acc 0.68
</br>
3. 단발성 데이터 + 감성대화 말뭉치
	</br>train acc 0.82
	</br>test acc 0.64
</br>
4. 연속적 데이터 + 단발성 데이터 + 감성대화 말뭉치 + 감정 분류를 위한 대화 음성 데이터셋
    </br>train acc 0.88
	</br>test acc 0.73
</br>
5. 단발성 데이터 + 감성대화 말뭉치 + 감정 분류를 위한 대화 음성 데이터셋
	</br>train acc 0.86
	</br>test acc 0.71  
6. 감성대화 말뭉치(감정 별 대표 문장) + 감정 분류를 위한 대화 음성 데이터셋
	</br>train acc 0.89
	</br>test acc 0.76
</br>
7. **감성대화 말뭉치 + 감정 분류를 위한 대화 음성 데이터셋**
	</br>**train acc 0.92**
	</br>**test acc 0.82**

> 7번의 구성에서 정확도가 가장 높은 것을 확인할 수 있었다.

**데이터 수집**
> 이번 프로젝트를 위해 사용한 한국어 대화 문장 데이터셋은 총 2개이다. </br>
4개의 데이터셋 중에 가장 정확도가 높은 구성으로 진행하였다.
</br>
1. 감성 대화 말뭉치
* 한국어 감성 데이터셋을 상세한 감정 라벨링(감정 대분류와 소분류로 구분)과 함께 제공하는 AIHub의 공공 데이터셋
* 약 4만 건의 데이터 셋 (기쁨, 슬픔, 당황, 분노, 불안, 상처의 6개 감정)
* 데이터 병합을 위해 감정 대분류와 대화 문장을 남기고, 감정 소분류는 누락
</br>
</br>
2. 감정 분류를 위한 대화 음성 데이터셋
* 감성대화 어플리케이션을 이용해 수집한 AIHUB의 공공 데이터셋
* 약 2만 건의 데이터 셋 (기쁨, 슬픔, 놀람, 분노, 공포, 혐오, 중립의 7개 감정)

# 3. 데이터 전처리

**데이터 전처리**

감정 분류를 위한 대화 음성 데이터셋 (7종류의 감정) </br>
: 공포 놀람 분노 슬픔 중립 행복 혐오 </br>
감성 대화 말뭉치 (6종류의 감정) </br>
: 기쁨 당황 분노 불안 상처 슬픔 </br>
</br>
<병합된 결과>
</br>
: 불안 분노 기쁨 슬픔 상처 (5) </br>
</br>
데이터셋을 살펴본 결과, 감성 대화 말뭉치의 '당황' 감정은 감정 분류를 위한 대화 음성 데이터셋의 '공포', '놀람' 감정과 중복된다. </br>
따라서 데이터셋을 병합하였다.

감성대화 말뭉치 데이터셋에서 각 행의 발화문 1, 발화문 2, 발화문 3을 한 문장으로 병합하였다. </br>
이 과정에서 발화문 3의 결측치가 다수 존재하여 이를 제거하였다.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

data1_train = pd.read_excel('/content/drive/MyDrive/dataset/감성대화말뭉치Training.xlsx')

data1_train.head()

,Unnamed: 0,연령,성별,상황키워드,신체질환,감정_대분류,감정_소분류,사람문장1,시스템문장1,사람문장2,시스템문장2,사람문장3,시스템문장3
0,1,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,일은 왜 해도 해도 끝이 없을까? 화가 난다.,많이 힘드시겠어요. 주위에 의논할 상대가 있나요?,그냥 내가 해결하는 게 나아. 남들한테 부담 주고 싶지도 않고.,혼자 해결하기로 했군요. 혼자서 해결하기 힘들면 주위에 의논할 사람을 찾아보세요.,NaN,NaN
1,2,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,이번 달에 또 급여가 깎였어! 물가는 오르는데 월급만 자꾸 깎이니까 너무 화가 나.,급여가 줄어 속상하시겠어요. 월급이 줄어든 것을 어떻게 보완하실 건가요?,최대한 지출을 억제해야겠어. 월급이 줄어들었으니 고정지출을 줄일 수밖에 없을 것 같아.,월급이 줄어든 만큼 소비를 줄일 계획이군요.,NaN,NaN
2,3,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,회사에 신입이 들어왔는데 말투가 거슬려. 그런 애를 매일 봐야 한다고 생각하니까 스...,회사 동료 때문에 스트레스를 많이 받는 것 같아요. 문제 해결을 위해 어떤 노력을 ...,잘 안 맞는 사람이랑 억지로 잘 지내는 것보단 조금은 거리를 두고 예의를 갖춰서 대...,스트레스받지 않기 위해선 인간관계에 있어 약간의 거리를 두는 게 좋겠군요.,NaN,NaN
3,4,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,직장에서 막내라는 이유로 나에게만 온갖 심부름을 시켜. 일도 많은 데 정말 분하고 ...,관련 없는 심부름을 모두 하게 되어서 노여우시군요. 어떤 것이 상황을 나아질 수 있...,직장 사람들과 솔직하게 이야기해보고 싶어. 일하는 데에 방해된다고.,직장 사람들과 이야기를 해 보겠다고 결심하셨군요.,NaN,NaN
4,5,청년,여성,"진로,취업,직장",해당없음,분노,노여워하는,얼마 전 입사한 신입사원이 나를 무시하는 것 같아서 너무 화가 나.,무시하는 것 같은 태도에 화가 나셨군요. 상대방의 어떤 행동이 그런 감정을 유발하는...,상사인 나에게 먼저 인사하지 않아서 매일 내가 먼저 인사한다고!,항상 먼저 인사하게 되어 화가 나셨군요. 어떻게 하면 신입사원에게 화났음을 표현할 ...,NaN,NaN

In [ ]:
data2 = pd.read_csv('/content/drive/MyDrive/dataset/대화음성데이터셋.csv', encoding='cp949')

data2.head()

,wav_id,발화문,상황,1번 감정,1번 감정세기,2번 감정,2번 감정세기,3번 감정,3번 감정세기,4번 감정,4번감정세기,5번 감정,5번 감정세기,나이,성별
0,5f4141e29dd513131eacee2f,헐! 나 이벤트에 당첨 됐어.,happiness,angry,2,surprise,2,happiness,2,happiness,2,happiness,2,48,female
1,5f4141f59dd513131eacee30,내가 좋아하는 인플루언서가 이벤트를 하더라고. 그래서 그냥 신청 한번 해봤지.,happiness,neutral,0,happiness,2,happiness,2,happiness,2,happiness,2,48,female
2,5f4142119dd513131eacee31,"한 명 뽑는 거였는데, 그게 바로 내가 된 거야.",happiness,angry,2,happiness,2,happiness,2,happiness,2,happiness,2,48,female
3,5f4142279dd513131eacee32,"당연히 마음에 드는 선물이니깐, 이벤트에 내가 신청 한번 해본 거지. 비싼 거야. ...",happiness,angry,2,happiness,2,happiness,2,happiness,2,happiness,1,48,female
4,5f3c9ed98a3c1005aa97c4bd,에피타이저 정말 좋아해. 그 것도 괜찮은 생각인 것 같애.,neutral,happiness,2,happiness,1,happiness,2,happiness,1,happiness,1,48,female

In [ ]:
import pandas as pd

data1_train = pd.read_excel('/content/drive/MyDrive/dataset/감성대화말뭉치Training.xlsx')
data1_validation = pd.read_excel('/content/drive/MyDrive/dataset/감성대화말뭉치Validation.xlsx')
data1 = pd.concat([data1_train, data1_validation])


# 감성 레이블을 정수로 변환 (0, 2, 3, 5)
data1.loc[(data1['감정_대분류'] == "불안"), '감정_대분류'] = 0 #불안 => 0
data1.loc[(data1['감정_대분류'] == "분노"), '감정_대분류'] = 2 #분노 => 2
data1.loc[(data1['감정_대분류'] == "슬픔"), '감정_대분류'] = 3 #슬픔 => 3
data1.loc[(data1['감정_대분류'] == "상처"), '감정_대분류'] = 3 #상처 => 3
data1.loc[(data1['감정_대분류'] == "기쁨"), '감정_대분류'] = 5 #기쁨 => 5

# 데이터셋에서 나누어져있는 '사람문장1, 사람문장2, 사람문장3'을 병합, 당황 감정 제거
data1 = data1.drop(data1[data1['감정_대분류'] == '당황'].index)
data1['사람문장'] = data1['사람문장1'].astype(str) + data1['사람문장2'].astype(str) + data1['사람문장3'].astype(str)

# 병합한 '사람문장1, 사람문장2, 사람문장3'에서 더해진 결측치 값을 제거
data1['사람문장'] = data1['사람문장'].str.replace('nan', '')

data1_list = []
for q, label in zip(data1['사람문장'], data1['감정_대분류'])  :
    data = []
    data.append(q)
    data.append(str(label))

    data1_list.append(data)

# 감성 레이블을 정수로 변환 (0~6)
data2.loc[(data2['상황'] == "fear"), '상황'] = 0       #공포 => 0
data2.loc[(data2['상황'] == "surprise"), '상황'] = 1   #놀람 => 1
data2.loc[(data2['상황'] == "angry"), '상황'] = 2      #분노 => 2
data2.loc[(data2['상황'] == "sadness"), '상황'] = 3    #슬픔 => 3
data2.loc[(data2['상황'] == "neutral"), '상황'] = 4    #중립 => 4
data2.loc[(data2['상황'] == "happiness"), '상황'] = 5  #행복 => 5
data2.loc[(data2['상황'] == "disgust"), '상황'] = 6    #혐오 => 6

data2_list = []
for q, label in zip(data2['발화문'], data2['상황']) :
    data = []
    data.append(q)
    data.append(str(label))

    data2_list.append(data)

merge_data = data1_list + data2_list

# 각 행의 글자 길이 계산
lengths = [len(row[0]) for row in merge_data]

# 평균 길이 계산
average_length = sum(lengths) / len(lengths)

print(f"모든 발화문의 평균 길이: {average_length:.2f} 글자")

모든 발화문의 평균 길이: 76.97 글자

# Colab 환경 설정

> 모델을 구현하기에 앞서 코랩 환경설정을 진행하려고 한다. </br>
해당 사양은 KoBERT 오픈소스 내 requirements.txt를 참고하였다.

In [ ]:
# Colab 환경 설정
# requirements : https://github.com/SKTBrain/KoBERT/blob/master/kobert_hf/requirements.txt
!pip install mxnet
!pip install gluonnlp==0.8.0
!pip install sentencepiece
!pip install transformers
!pip install torch
!pip install tqdm pandas
!pip install numpy==1.23.1
!pip install "transformers==4.28.1" "kobert-tokenizer==0.1"

> 다음으로 깃허브 내 파일을 Colab으로 가져온다.

In [ ]:
# https://github.com/SKTBrain/KoBERT의 파일들을 Colab으로 다운로드
!pip install 'git+https://github.com/SKTBrain/KoBERT.git#egg=kobert_tokenizer&subdirectory=kobert_hf'

> 그 다음으로는 해당 라이브러리들을 import 해준다.

In [ ]:
# Transformers
from transformers import BertModel, AutoTokenizer
from transformers.optimization import get_cosine_schedule_with_warmup

# Setting Library
import pandas as pd
import torch
from torch import nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
if not hasattr(np, 'bool'):
    np.bool = bool
import gluonnlp as nlp
from tqdm.notebook import tqdm
import pandas as pde
from sklearn.model_selection import train_test_split
from huggingface_hub import hf_hub_download

In [ ]:
device = torch.device("cuda:0")

In [ ]:
tokenizer = AutoTokenizer.from_pretrained('monologg/kobert', trust_remote_code=True)
bertmodel = BertModel.from_pretrained('skt/kobert-base-v1', return_dict=False)

# Setting parameters
max_len = 64
batch_size = 64
warmup_ratio = 0.1
num_epochs = 5
max_grad_norm = 1
log_interval = 200
learning_rate =  5e-5

In [ ]:
class BERTDataset(Dataset):
    def __init__(self, dataset, sent_idx, label_idx, bert_tokenizer, max_len, pad, pair):
        self.dataset = dataset
        self.sent_idx = sent_idx
        self.label_idx = label_idx
        self.tokenizer = bert_tokenizer
        self.max_len = max_len

    def __getitem__(self, i):
        # 데이터에서 텍스트와 라벨 추출
        text = str(self.dataset[i][self.sent_idx])
        label = np.int32(self.dataset[i][self.label_idx])

        encoding = self.tokenizer(
            text,
            padding='max_length',
            max_length=self.max_len,
            truncation=True,
            return_token_type_ids=True,
            return_tensors='pt'
        )

        token_ids = encoding['input_ids'].squeeze(0)

        if 'token_type_ids' in encoding:
            segment_ids = encoding['token_type_ids'].squeeze(0)
        else:
            segment_ids = torch.zeros(self.max_len, dtype=torch.long)

        valid_length = torch.sum(encoding['attention_mask']).item()

        return token_ids, valid_length, segment_ids, label

    def __len__(self):
        return len(self.dataset)

> BERT 데이터셋을 구성하는 라벨의 개수를 num_classes로 설정할 수 있다.

In [ ]:
# class BERTClassifier
class BERTClassifier(nn.Module):
    def __init__(self,
                 bert,
                 hidden_size = 768,
                 num_classes=7,
                 dr_rate=None,
                 params=None):
        super(BERTClassifier, self).__init__()
        self.bert = bert
        self.dr_rate = dr_rate

        self.classifier = nn.Linear(hidden_size , num_classes)
        if dr_rate:
            self.dropout = nn.Dropout(p=dr_rate)

    def gen_attention_mask(self, token_ids, valid_length):
        attention_mask = torch.zeros_like(token_ids)
        for i, v in enumerate(valid_length):
            attention_mask[i][:v] = 1
        return attention_mask.float()

    def forward(self, token_ids, valid_length, segment_ids):
        attention_mask = self.gen_attention_mask(token_ids, valid_length)

        _, pooler = self.bert(input_ids = token_ids, token_type_ids = segment_ids.long(), attention_mask = attention_mask.float().to(token_ids.device), return_dict=False)
        if self.dr_rate:
            out = self.dropout(pooler)
        return self.classifier(out)

In [ ]:
# 소프트 맥스 추가
def new_softmax(a) :
    c = np.max(a) # 최댓값
    exp_a = np.exp(a-c) # 각각의 원소에 최댓값을 뺀 값에 exp를 취한다. (이를 통해 overflow 방지)
    sum_exp_a = np.sum(exp_a)
    y = (exp_a / sum_exp_a) * 100
    return np.round(y, 1)

In [ ]:
def predict(sentence, chunk_size=77):
    # 텍스트를 평균 길이로 나눔
    chunks = [sentence[i:i + chunk_size] for i in range(0, len(sentence), chunk_size)]
    all_emotions = []

    for chunk in chunks:
        dataset = [[chunk, '0']]
        test = BERTDataset(dataset, 0, 1, tokenizer, max_len, True, False)
        test_dataloader = torch.utils.data.DataLoader(test, batch_size=batch_size, num_workers=2)
        model.eval()
        for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(test_dataloader):
            token_ids = token_ids.long().to(device)
            segment_ids = segment_ids.long().to(device)
            valid_length = valid_length
            label = label.long().to(device)
            out = model(token_ids, valid_length, segment_ids)

            emotions = ["공포", "놀람", "분노", "슬픔", "중립", "행복", "혐오"]
            for i in out:
                logits = i.detach().cpu().numpy()
                probabilities = new_softmax(logits).tolist()
                emotion_probs = {emotions[idx]: round(prob, 1) for idx, prob in enumerate(probabilities)}
                all_emotions.append((emotion_probs, len(chunk)))

    # 전체 감정을 종합
    final_emotion = combine_emotions(all_emotions)
    print(final_emotion)

def combine_emotions(emotions_list):
    combined = {}
    total_length = sum(length for _, length in emotions_list)

    for emotions, length in emotions_list:
        for emotion, prob in emotions.items():
            if emotion not in combined:
                combined[emotion] = 0
            combined[emotion] += prob * (length / total_length)  # 길이로 가중 평균

    return {emotion: round(prob, 2) for emotion, prob in combined.items()}

In [ ]:
train_set, test_set = train_test_split(merge_data, test_size=0.2, shuffle=True, random_state=20)

data_train = BERTDataset(train_set, 0, 1, tokenizer, max_len, True, False)
data_test = BERTDataset(test_set, 0, 1, tokenizer, max_len, True, False)
train_dataloader = torch.utils.data.DataLoader(data_train, batch_size=batch_size, num_workers=2)
test_dataloader = torch.utils.data.DataLoader(data_test, batch_size=batch_size, num_workers=2)

In [ ]:
model = BERTClassifier(bertmodel, dr_rate=0.5).to(device)

# Prepare optimizer and schedule (linear warmup and decay)
no_decay = ['bias', 'LayerNorm.weight']
optimizer_grouped_parameters = [
    {'params': [p for n, p in model.named_parameters() if not any(nd in n for nd in no_decay)], 'weight_decay': 0.01},
    {'params': [p for n, p in model.named_parameters() if any(nd in n for nd in no_decay)], 'weight_decay': 0.0}
]
optimizer = torch.optim.AdamW(optimizer_grouped_parameters, lr=learning_rate)
loss_fn = nn.CrossEntropyLoss()
t_total = len(train_dataloader) * num_epochs
warmup_step = int(t_total * warmup_ratio)
scheduler = get_cosine_schedule_with_warmup(optimizer, num_warmup_steps=warmup_step, num_training_steps=t_total)

In [ ]:
# 정확도 측정을 위한 함수 정의
def calc_accuracy(X,Y):
    max_vals, max_indices = torch.max(X, 1)
    train_acc = (max_indices == Y).sum().data.cpu().numpy()/max_indices.size()[0]
    return train_acc

for e in range(num_epochs):
    train_acc = 0.0
    test_acc = 0.0
    model.train()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm(train_dataloader)):
        optimizer.zero_grad()
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        loss = loss_fn(out, label)
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_grad_norm)
        optimizer.step()
        scheduler.step()  # Update learning rate schedule
        train_acc += calc_accuracy(out, label)
        if batch_id % log_interval == 0:
            print("epoch {} batch id {} loss {} train acc {}".format(e+1, batch_id+1, loss.data.cpu().numpy(), train_acc / (batch_id+1)))
    print("epoch {} train acc {}".format(e+1, train_acc / (batch_id+1)))
    model.eval()
    for batch_id, (token_ids, valid_length, segment_ids, label) in enumerate(tqdm(test_dataloader)):
        token_ids = token_ids.long().to(device)
        segment_ids = segment_ids.long().to(device)
        valid_length= valid_length
        label = label.long().to(device)
        out = model(token_ids, valid_length, segment_ids)
        test_acc += calc_accuracy(out, label)
    print("epoch {} test acc {}".format(e+1, test_acc / (batch_id+1)))

  0%|          | 0/827 [00:00<?, ?it/s]

epoch 1 batch id 1 loss 2.1050493717193604 train acc 0.09375
epoch 1 batch id 201 loss 1.0870177745819092 train acc 0.396455223880597
epoch 1 batch id 401 loss 0.6276000738143921 train acc 0.5575124688279302
epoch 1 batch id 601 loss 0.5751808881759644 train acc 0.6281977953410982
epoch 1 batch id 801 loss 0.7567030787467957 train acc 0.6672518726591761
epoch 1 train acc 0.6709663900186874

  0%|          | 0/207 [00:00<?, ?it/s]

epoch 1 test acc 0.8029610437029547

  0%|          | 0/827 [00:00<?, ?it/s]

epoch 2 batch id 1 loss 0.38913145661354065 train acc 0.90625
epoch 2 batch id 201 loss 0.541563868522644 train acc 0.7984297263681592
epoch 2 batch id 401 loss 0.4689798951148987 train acc 0.8067331670822943
epoch 2 batch id 601 loss 0.4159168303012848 train acc 0.8162437603993344
epoch 2 batch id 801 loss 0.48339036107063293 train acc 0.8209464731585518
epoch 2 train acc 0.8213404831263054

  0%|          | 0/207 [00:00<?, ?it/s]

epoch 2 test acc 0.8133777103696214

  0%|          | 0/827 [00:00<?, ?it/s]

epoch 3 batch id 1 loss 0.28980007767677307 train acc 0.90625
epoch 3 batch id 201 loss 0.2759193778038025 train acc 0.8446050995024875
epoch 3 batch id 401 loss 0.33890432119369507 train acc 0.8498285536159601
epoch 3 batch id 601 loss 0.21807032823562622 train acc 0.8580230865224625
epoch 3 batch id 801 loss 0.3552854657173157 train acc 0.862125468164794
epoch 3 train acc 0.8625250769484445

  0%|          | 0/207 [00:00<?, ?it/s]

epoch 3 test acc 0.8195673238961915

  0%|          | 0/827 [00:00<?, ?it/s]

epoch 4 batch id 1 loss 0.20225170254707336 train acc 0.90625
epoch 4 batch id 201 loss 0.17994746565818787 train acc 0.8842506218905473
epoch 4 batch id 401 loss 0.24228209257125854 train acc 0.891949812967581
epoch 4 batch id 601 loss 0.17803868651390076 train acc 0.8981905158069884
epoch 4 batch id 801 loss 0.2861599326133728 train acc 0.9017439138576779
epoch 4 train acc 0.9018151588435748

  0%|          | 0/207 [00:00<?, ?it/s]

epoch 4 test acc 0.8228885799348388

  0%|          | 0/827 [00:00<?, ?it/s]

epoch 5 batch id 1 loss 0.13132214546203613 train acc 0.96875
epoch 5 batch id 201 loss 0.10959958285093307 train acc 0.9125466417910447
epoch 5 batch id 401 loss 0.20211206376552582 train acc 0.9193422693266833
epoch 5 batch id 601 loss 0.14390142261981964 train acc 0.9252027870216306
epoch 5 batch id 801 loss 0.3193005919456482 train acc 0.9268102372034956
epoch 5 train acc 0.9267804633395624

  0%|          | 0/207 [00:00<?, ?it/s]

epoch 5 test acc 0.8197937731715538

| Epoch | Train Acc | Test Acc |
| ----: | --------: | -------: |
|     1 |      0.67 |     0.80 |
|     2 |      0.82 |     0.81 |
|     3 |      0.86 |     0.81 |
|     4 |      0.90 |     0.82 |
|     5 |      0.92 |     0.81 |

> Epoch 4에서 테스트 정확도가 최고 성능(0.82)에 도달하였으며, </br>
이후에는 학습 정확도만 증가하고 테스트 정확도는 향상되지 않아 과적합을 확인할 수 있었다.

In [ ]:
torch.save(model, f'/content/drive/MyDrive/Colab Notebooks/SentimentAnalysisKOBert.pt')
torch.save(model.state_dict(), f'/content/drive/MyDrive/Colab Notebooks/SentimentAnalysisKOBert_StateDict.pt')

> 모델 저장

- SentimentAnalysisKOBert.pt : 모델 구조와 학습된 가중치를 함께 저장한 파일
- SentimentAnalysisKOBert_StateDict.pt : 학습된 가중치(State Dictionary)만 저장한 파일

추론 단계에서는 PyTorch의 권장 방식에 따라 `State Dictionary`를 불러와 모델 구조에 적용하여 사용